In [151]:
import pandas as pd
import os
import numpy as np
filepath = ("../ml4t/data/")

In [164]:
np.ones([4,2], dtype = np.integer)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [165]:
a = np.random.randint(0,10, size = [5,4])

In [168]:
a

array([[3, 7, 2, 2],
       [2, 4, 7, 7],
       [1, 7, 1, 8],
       [7, 7, 1, 1],
       [5, 6, 2, 6]])

In [166]:
a.sum(axis=0)

array([18, 31, 13, 24])

In [167]:
a.sum(axis=1)

array([14, 20, 17, 16, 19])

In [169]:
a.min(axis = 0)

array([1, 4, 1, 1])

In [171]:
np.array([1,2,3])/2

array([0, 1, 1])